---
development:
  cloud_name: <%= Rails.application.credentials.production[:cloud_name] %>
  api_key: <%= Rails.application.credentials.production[:api_key] %>
  api_secret: <%= Rails.application.credentials.production[:api_secret] %>
  enhance_image_tag: <%= Rails.application.credentials.production[:enhance_image_tag] %>
  static_image_support: <%= Rails.application.credentials.production[:enhance_image_support] %>

test:
  cloud_name:  <%= Rails.application.credentials.production[:cloud_name] %>
  api_key: <%= Rails.application.credentials.production[:api_key] %>
  api_secret: <%= Rails.application.credentials.production[:api_secret] %>
  enhance_image_tag: <%= Rails.application.credentials.production[:enhance_image_tag] %>
  static_image_support: <%= Rails.application.credentials.production[:enhance_image_support] %>

production:
  cloud_name: <%= Rails.application.credentials.production[:cloud_name] %>
  api_key: <%= Rails.application.credentials.production[:api_key] %>
  api_secret: <%= Rails.application.credentials.production[:api_secret] %>
  enhance_image_tag: <%= Rails.application.credentials.production[:enhance_image_tag] %>
  static_image_support: <%= Rails.application.credentials.production[:enhance_image_support] %>
