DEV_DATABASE: 'seyoumb'
DB_USERNAME: 'fena'
DB_PASSWORD: 'fenet 1986&'
DB_HOST: 'localhost'
DB_PORT: '5432'

TEST_DATABASE: 'seyoumb'

#HISAB_DATABASE_PASSWORD: '000000'

#ADMIN_FULLNAME: 'hisabyebet'
#ADMIN_EMAIL: 'hisabyebet@gmail.com'
#SEED_PASSWORD: 'hisab1234'
#ROLE: 'Owner'
