DEV_DATABASE: 'seyoumb'
DB_USERNAME: 'fena'
DB_PASSWORD: 'fenet 1986&'
DB_HOST: 'localhost'
DB_PORT: '5432'

TEST_DATABASE: 'seyoumb'




#ADMIN_EMAIL: 'hisabyebet@gmail.com'
#SEED_PASSWORD: 'hisab1234'
